### ISSUE TITLE
Unescaped newlines in single-quoted literals

### ISSUE THREAD

**Issue by wouterbeek** [nheist/CaLiGraph#2]
We are unable to read file `caligraph-instances_labels.nt.bz2` because a single-quoted literal on line 912,449 contains an unescaped newline:

```ttl
<http://caligraph.org/resource/Analogy_of_the_divided_line> <http://www.w3.org/2004/02/skos/core#altLabel> "Divided line of
 Plato" .
```

There are two possible fixes here:

  - Escape the newline, e.g., with backslag encoding (`\n`).
  - Use as triple-quoted literal:

```ttl
<http://caligraph.org/resource/Analogy_of_the_divided_line> <http://www.w3.org/2004/02/skos/core#altLabel> """Divided line of
 Plato""" .
```

**Comment by nheist** [comment]
Dear Wouter,
thank you for reporting this issue. The problems seems to occur only in older versions of CaLiGraph as I can't reproduce it with files of version 1.3.x. Using the newest version 1.3.1 (e.g. directly from Zenodo [1] or from the CaLiGraph website) should thus help you out. Let me know if you run into any other issues.
Thanks and all the best,
Nico

[1] https://zenodo.org/record/4419708

**Comment by nheist** [comment]
The Zenodo website itself had some issues today - I also got some 404 errors when I tried to download something today. However, I just tried the link you posted (https://zenodo.org/api/files/042e92ff-0bf7-4d3a-8edb-a5bf491f9a19/caligraph-instances_labels.nt.bz2) and it worked for me. Maybe just try it again.

The last URL you posted (https://zenodo.org/record/4050308/files/caligraph-instances_labels.nt.bz2?download=1) is actually outdated as it points to an older version of the CaLiGraph labels. Maybe you need to clear your cache for the page http://caligraph.org/resources.html - otherwise I can't explain why you should get this old link.

**Comment by wouterbeek** [comment]
> The last URL you posted (https://zenodo.org/record/4050308/files/caligraph-instances_labels.nt.bz2?download=1) is actually outdated as it points to an older version of the CaLiGraph labels. Maybe you need to clear your cache for the page http://caligraph.org/resources.html - otherwise I can't explain why you should get this old link.

I was indeed using a cached version of the resources page :-/  Thanks for helping me out!
